(switch-to-buffer "*scratch*")
(insert-char "T")
(insert-char "h")
(insert-char "i")
(insert-char "s")
(insert-char " ")
(insert-char "i")
(insert-char "s")
(insert-char " ")
(insert-char "c")
(insert-char "o")
(insert-char "o")
(insert-char "l")
(insert-char "!")
(insert-char ".")
(switch-to-buffer "switch_to_buffer.input")
(insert-char "T")
(insert-char "h")
(insert-char "i")
(insert-char "s")
(insert-char " ")
(insert-char "i")
(insert-char "s")
(insert-char " ")
(insert-char "n")
(insert-char "o")
(insert-char "t")
(insert-char ".")
