; FIXME: Next line should not be needed
(setq sentence-end-double-space nil)
(set-mark )
(forward-line)
(forward-line)
(kill-region  )
(yank)
(yank)
(open-line)
(forward-line)
(yank)
(forward-line)
(set-fill-column 3)
(fill-paragraph)
(forward-line -1)
(forward-line -1)
(forward-line -1)
(set-fill-column 12)
(fill-paragraph)
(forward-line -1)
(forward-line -1)
(forward-line -1)
(forward-line -1)
(forward-line -1)
(forward-line -1)
(end-of-line)
(set-fill-column 33)
(fill-paragraph)
(save-buffer)
(save-buffers-kill-emacs)
