(forward-char)
(transpose-chars 1)
(transpose-chars 1)
(transpose-chars 1)
(transpose-chars 1)
(transpose-chars 1)
(transpose-chars 1)
(transpose-chars 1)
(transpose-chars 1)
(transpose-chars 1)
(transpose-chars 1)
(transpose-chars 1)
(save-buffer)
(save-buffers-kill-emacs)
