(start-kbd-macro)
(insert-char "")
(insert-char "c")
(end-kbd-macro)
(insert-char "")
(insert-char "x")
(insert-char "n")
(insert-char "a")
(insert-char "m")
(insert-char "e")
(insert-char "-")
(insert-char "l")
(insert-char "a")
(insert-char "s")
(insert-char "t")
(insert-char "-")
(insert-char "k")
(insert-char "b")
(insert-char "d")
(insert-char "-")
(insert-char "m")
(insert-char "a")
(insert-char "c")
(insert-char "r")
(insert-char "o")
(newline)
(insert-char "f")
(insert-char "o")
(insert-char "o")
(newline)
(insert-char "")
(insert-char "x")
(insert-char "f")
(insert-char "o")
(insert-char "o")
(newline)
(insert-char "")
(insert-char "x")
(insert-char "f")
(insert-char "o")
(insert-char "o")
(newline)
