(end-of-line)
(insert-char " ")
(insert-char "I")
(insert-char " ")
(insert-char "a")
(insert-char "m")
(insert-char " ")
(insert-char "n")
(insert-char "o")
(insert-char "w")
(insert-char " ")
(insert-char "g")
(insert-char "o")
(insert-char "i")
(insert-char "n")
(insert-char "g")
(insert-char " ")
(insert-char "t")
(insert-char "o")
(insert-char " ")
(insert-char "m")
(insert-char "a")
(insert-char "k")
(insert-char "e")
(insert-char " ")
(insert-char "t")
(insert-char "h")
(insert-char "e")
(insert-char " ")
(insert-char "l")
(insert-char "i")
(insert-char "n")
(insert-char "e")
(insert-char " ")
(insert-char "s")
(insert-char "u")
(insert-char "f")
(insert-char "f")
(insert-char "i")
(insert-char "c")
(insert-char "i")
(insert-char "e")
(insert-char "n")
(insert-char "t")
(insert-char "l")
(insert-char "y")
(insert-char " ")
(insert-char "l")
(insert-char "o")
(insert-char "n")
(insert-char "g")
(insert-char " ")
(insert-char "t")
(insert-char "h")
(insert-char "a")
(insert-char "t")
(insert-char " ")
(insert-char "I")
(insert-char " ")
(insert-char "c")
(insert-char "a")
(insert-char "n")
(insert-char " ")
(insert-char "w")
(insert-char "r")
(insert-char "a")
(insert-char "p")
(insert-char " ")
(insert-char "i")
(insert-char "t")
(insert-char ".")
(fill-paragraph)
(save-buffer)
(save-buffers-kill-emacs)
