(forward-char)
(forward-char)
(forward-char)
(forward-char)
(forward-char)
(forward-char)
(insert-char ")")
(beginning-of-line)
(insert-char "(")
(beginning-of-line)
(forward-sexp)
(insert-char "a")
(save-buffer)
(save-buffers-kill-emacs)
