(next-line)
(next-line)
(indent-relative)
(insert-char "f")
(indent-relative)
(insert-char "f")
(insert-char "f")
(insert-char "f")
(insert-char "f")
(insert-char "f")
(indent-relative)
(insert-char "a")
(insert-char "a")
(insert-char "a")
(save-buffer)
(save-buffers-kill-emacs)
