(forward-line)
(forward-word)
(forward-word)
(kill-line)
(forward-line)
(forward-line)
(kill-line -1)
(forward-line -1)
(forward-line -1)
(end-of-line)
(kill-line 0)
(save-buffer)
(save-buffers-kill-emacs)
