(set-mark (point))
(copy-to-register 49 (point) (mark))
(list-registers)
(other-window 1)
(set-mark (point))
(forward-line)
(copy-region-as-kill (point) (mark))
(other-window -1)
(yank)
(save-buffer)
(save-buffers-kill-emacs)
