(forward-word)
(insert-char "(")
(forward-word)
(forward-word)
(forward-word)
(insert-char ")")
(backward-word)
(backward-word)
(backward-char)
(backward-char)
(backward-char)
(backward-char)
(backward-char)
(mark-sexp)
(kill-region)
(save-buffer)
(save-buffers-kill-zile)
