(set-mark-command)
(next-line)
(next-line)
(kill-region)
(yank)
(yank)
(open-line)
(next-line)
(yank)
(next-line)
(set-fill-column 3)
(fill-paragraph)
(previous-line)
(previous-line)
(previous-line)
(set-fill-column 12)
(fill-paragraph)
(previous-line)
(previous-line)
(previous-line)
(previous-line)
(previous-line)
(previous-line)
(end-of-line)
(set-fill-column 33)
(fill-paragraph)
(save-buffer)
(save-buffers-kill-zile)
