(insert "        ")
(next-line)
(beginning-of-line)
(insert "       ")
(next-line)
(next-line)
(beginning-of-line)
(insert "        ")
(next-line)
(mark-whole-buffer)
(tabify)
(save-buffer)
(save-buffers-kill-emacs)
