(insert "        ")
(forward-line)
(beginning-of-line)
(insert "       ")
(forward-line)
(forward-line)
(beginning-of-line)
(insert "        ")
(forward-line)
(mark-whole-buffer)
(tabify (point) (mark))
(save-buffer)
(save-buffers-kill-emacs)
