(insert-char " ")
(insert-char " ")
(insert-char " ")
(insert-char " ")
(insert-char " ")
(insert-char " ")
(insert-char " ")
(insert-char " ")
(next-line)
(beginning-of-line)
(insert-char " ")
(insert-char " ")
(insert-char " ")
(insert-char " ")
(insert-char " ")
(insert-char " ")
(insert-char " ")
(next-line)
(next-line)
(beginning-of-line)
(insert-char " ")
(insert-char " ")
(insert-char " ")
(insert-char " ")
(insert-char " ")
(insert-char " ")
(insert-char " ")
(insert-char " ")
(next-line)
(mark-whole-buffer)
(tabify)
(save-buffer)
(save-buffers-kill-zile)
