(transient-mark-mode)
(set-mark-command)
(next-line)
(next-line)
(insert-char "t")
(insert-char "h")
(insert-char "i")
(insert-char "s")
(kill-region)
(insert-char "t")
(insert-char "h")
(insert-char "a")
(insert-char "t")
(save-buffer)
(save-buffers-kill-emacs)
