(insert "	")
(next-line)
(beginning-of-line)
(insert "	")
(beginning-of-line)
(previous-line)
(set-mark-command)
(next-line)
(next-line)
(next-line)
(next-line)
(untabify)
(save-buffer)
(save-buffers-kill-emacs)
