(insert "	")
(forward-line)
(insert "	")
(forward-line -1)
(set-mark (point))
(forward-line)
(forward-line)
(forward-line)
(forward-line)
(untabify (mark) (point))
(save-buffer)
(save-buffers-kill-emacs)
