/* Default keyboard bindings.

   Copyright (c) 2008 Free Software Foundation, Inc.
   Copyright (c) 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004 Sandro Sigala.
   Copyright (c) 2003, 2004, 2005, 2006, 2007, 2008 Reuben Thomas.
   Copyright (c) 2004 David Capello.

   This file is part of GNU Zile.

   GNU Zile is free software; you can redistribute it and/or modify it
   under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 3, or (at your option)
   any later version.

   GNU Zile is distributed in the hope that it will be useful, but
   WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with GNU Zile; see the file COPYING.  If not, write to the
   Free Software Foundation, Fifth Floor, 51 Franklin Street, Boston,
   MA 02111-1301, USA.  */

X (back_to_indentation, "\\M-m")
X (backward_char, "\\C-b")
X (backward_char, "\\LEFT")
X (backward_delete_char, "\\BACKSPACE")
X (backward_kill_word, "\\M-\\BACKSPACE")
X (backward_paragraph, "\\M-{")
X (backward_sexp, "\\C-\\M-b")
X (backward_word, "\\M-b")
X (beginning_of_buffer, "\\M-<")
X (beginning_of_line, "\\C-a")
X (beginning_of_line, "\\HOME")
X (call_last_kbd_macro, "\\C-xe")
X (capitalize_word, "\\M-c")
X (copy_region_as_kill, "\\M-w")
X (copy_to_register, "\\C-xrx")
X (copy_to_register, "\\C-xrs")
X (delete_blank_lines, "\\C-x\\C-o")
X (delete_char, "\\C-d")
X (delete_char, "\\DELETE")
X (delete_horizontal_space, "\\M-\\\\")
X (delete_other_windows, "\\C-x1")
X (delete_window, "\\C-x0")
X (describe_bindings, "\\C-hb")
X (describe_bindings, "\\F1b")
X (describe_function, "\\C-hf")
X (describe_function, "\\F1f")
X (describe_key, "\\C-hk")
X (describe_key, "\\F1k")
X (describe_variable, "\\C-hv")
X (describe_variable, "\\F1v")
X (downcase_region, "\\C-x\\C-l")
X (downcase_word, "\\M-l")
X (end_kbd_macro, "\\C-x)")
X (end_of_buffer, "\\M->")
X (end_of_line, "\\C-e")
X (end_of_line, "\\END")
X (enlarge_window, "\\C-x^")
X (exchange_point_and_mark, "\\C-x\\C-x")
X (execute_extended_command, "\\M-x")
X (fill_paragraph, "\\M-q")
X (find_alternate_file, "\\C-x\\C-v")
X (find_file, "\\C-x\\C-f")
X (find_file_read_only, "\\C-x\\C-r")
X (forward_char, "\\RIGHT")
X (forward_char, "\\C-f")
X (forward_paragraph, "\\M-}")
X (forward_sexp, "\\C-\\M-f")
X (forward_word, "\\M-f")
X (goto_line, "\\M-gg")
X (goto_line, "\\M-g\\M-g")
X (indent_for_tab_command, "\\TAB")
X (insert_file, "\\C-xi")
X (insert_register, "\\C-xrg")
X (insert_register, "\\C-xri")
X (isearch_backward, "\\C-r")
X (isearch_backward_regexp, "\\C-\\M-r")
X (isearch_forward, "\\C-s")
X (isearch_forward_regexp, "\\C-\\M-s")
X (just_one_space, "\\M-\\SPC")
X (keyboard_quit, "\\C-g")
X (kill_buffer, "\\C-xk")
X (kill_line, "\\C-k")
X (kill_region, "\\C-w")
X (kill_sexp, "\\C-\\M-k")
X (kill_word, "\\M-d")
X (list_buffers, "\\C-x\\C-b")
X (mark_paragraph, "\\M-h")
X (mark_sexp, "\\C-\\M-@")
X (mark_whole_buffer, "\\C-xh")
X (mark_word, "\\M-@")
X (newline, "\\RET")
X (newline_and_indent, "\\C-j")
X (next_line, "\\C-n")
X (next_line, "\\DOWN")
X (open_line, "\\C-o")
X (other_window, "\\C-xo")
X (overwrite_mode, "\\INSERT")
X (previous_line, "\\C-p")
X (previous_line, "\\UP")
X (query_replace, "\\M-%")
X (quoted_insert, "\\C-q")
X (recenter, "\\C-l")
X (save_buffer, "\\C-x\\C-s")
X (save_buffers_kill_zile, "\\C-x\\C-c")
X (save_some_buffers, "\\C-xs")
X (scroll_down, "\\M-v")
X (scroll_down, "\\PRIOR")
X (scroll_up, "\\C-v")
X (scroll_up, "\\NEXT")
X (set_fill_column, "\\C-xf")
X (set_mark_command, "\\C-@")
X (shell_command, "\\M-!")
X (shell_command_on_region, "\\M-|")
X (split_window, "\\C-x2")
X (start_kbd_macro, "\\C-x(")
X (suspend_zile, "\\C-x\\C-z")
X (suspend_zile, "\\C-z")
X (switch_to_buffer, "\\C-xb")
X (tab_to_tab_stop, "\\M-i")
X (toggle_read_only, "\\C-x\\C-q")
X (transpose_chars, "\\C-t")
X (transpose_lines, "\\C-x\\C-t")
X (transpose_sexps, "\\C-\\M-t")
X (transpose_words, "\\M-t")
X (undo, "\\C-xu")
X (undo, "\\C-_")
X (universal_argument, "\\C-u")
X (upcase_region, "\\C-x\\C-u")
X (upcase_word, "\\M-u")
X (view_zile_FAQ, "\\C-h\\C-f")
X (view_zile_FAQ, "\\F1\\C-f")
X (where_is, "\\C-hw")
X (where_is, "\\F1w")
X (write_file, "\\C-x\\C-w")
X (yank, "\\C-y")
