; undo in Emacs undoes everything from the start of the script (cf. fill-paragraph_2.el)
(delete-char 1)
(delete-char 1)
(delete-char 1)
(delete-char 1)
(undo)
(undo)
(undo)
(save-buffer)
(save-buffers-kill-emacs)
